### ISSUE TITLE
submit form 

### ISSUE THREAD

**Issue by jeinglis** [enochtsang/flock-information-database#17]
Enoch did pretty much all of it just need to add some fields that weren't  in the original form to fit our EER (Enterprise.submissionDate, veterinary practice, poultry supplier, etc)

**Comment by ExtraGravity** [comment]
The submissionDate we should be able to grab the current datetime and not have to ask the user for it.

Can you give me a list of things that I need to add?

**Comment by jeinglis** [comment]
I'll get a list together. The database needs to be fixed up so the two kindof go hand and hand.

**Comment by ExtraGravity** [comment]
Makes sense, I'll wait until then.

**Comment by jeinglis** [comment]
//add fields on general page: 
Number Of Birds Placed : number-of-birds-placed
Produces For : produces-for
Veterinary Practice Name : vet-name
Veterinary Practice Address : vet-address

//change section B to use single date fields rather than month and day fields

name them: (I put all fields that I have for catching and processing)

planned-catching-date-time
actual-catching-date-time

planned-processing-date-time
last-water-access-time
feed-disruption
feed-withdrawal-time
food-no-access-date
floor-1-time
floor-2-time
floor-3-time

**Comment by ExtraGravity** [comment]
GENERAL
- Number of birds placed is already there
  Added produces-for, vet-name, and vet-address

SECTION B
Instead of datetime, we are separating date and time as we discussed.

So now there is:
planned-catching-date
planned-catching-time

actual-catching-time

planned-processing-date
planned-processing-time

last-water-access-time

feed-distription (values is "yes" and "no")

food-no-access-date
floor-1-time
floor-2-time
floor-3-time
